<a href="https://colab.research.google.com/github/siro844/Machine_Learning/blob/main/tensors_and_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_0D=tf.constant(4)

In [ ]:
tensor_1D=tf.constant([2,0,-3])

In [ ]:
tensor_1D

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2,  0, -3], dtype=int32)>

In [8]:
tensor_2D=tf.constant(
    [
        [2,0,-2],
        [1,6,5]
    ]
)

In [9]:
tensor_2D

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  0, -2],
       [ 1,  6,  5]], dtype=int32)>

In [10]:
tensor_3D=tf.constant(
    [
        [
            [2,0,-2],
            [2,0,-2],
            [2,0,-2],
        ],
        [
            [2,0,-2],
            [2,0,-2],
            [2,0,-2],
        ]
    ]
)

In [11]:
tensor_3D

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 2,  0, -2],
        [ 2,  0, -2],
        [ 2,  0, -2]],

       [[ 2,  0, -2],
        [ 2,  0, -2],
        [ 2,  0, -2]]], dtype=int32)>

In [12]:
tensor_4D=tf.constant(
    [
         [
        [
            [2,0,-2],
            [2,0,-2],
            [2,0,-2],
        ],
        [
            [2,0,-2],
            [2,0,-2],
            [2,0,-2],
        ]
    ],
         [
        [
            [2,0,-2],
            [2,0,-2],
            [2,0,-2],
        ],
        [
            [2,0,-2],
            [2,0,-2],
            [2,0,-2],
        ]
    ],
    ]
)

In [13]:
tensor_4D

<tf.Tensor: shape=(2, 2, 3, 3), dtype=int32, numpy=
array([[[[ 2,  0, -2],
         [ 2,  0, -2],
         [ 2,  0, -2]],

        [[ 2,  0, -2],
         [ 2,  0, -2],
         [ 2,  0, -2]]],


       [[[ 2,  0, -2],
         [ 2,  0, -2],
         [ 2,  0, -2]],

        [[ 2,  0, -2],
         [ 2,  0, -2],
         [ 2,  0, -2]]]], dtype=int32)>

In [14]:
tensor_string=tf.constant("hello world")

In [15]:
tensor_string

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [16]:
import numpy as np

In [17]:
np_array=np.array([1,2,4])

In [18]:
converted_tensor=tf.convert_to_tensor(np_array)

In [20]:
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [25]:
#Identity Matrix or batch of matrices
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

In [26]:
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [27]:
filled_tensor=tf.fill(
    [3,4],5,name=None
)

In [28]:
filled_tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int32)>

In [29]:
one_tensor=tf.ones(
    [3,3,3],name=None
)

In [30]:
one_tensor


<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [33]:
#casting
one_tensor=tf.cast(one_tensor,dtype=tf.int32),
one_tensor

(<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
 array([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],
 
        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=int32)>,)

In [34]:
ones_like_tensor=tf.ones_like(filled_tensor)

In [35]:
ones_like_tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [37]:
#returns rank
tf.rank(ones_like_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>